on:
  rss:
    url: https://weekly.75.team/rss
    config:
      limit: 1
      timeZone: Asia/Shanghai
jobs:
  operation:
    name: Rss Operation
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          link: ${{on.rss.outputs.link}}
          pubDate: ${{on.rss.outputs.pubDate}}
          guid: ${{on.rss.outputs.guid}}
          content: ${{on.rss.outputs.content}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          description: ${{on.rss.outputs.description}}
          outputs: ${{on.rss.outputs}}
        run: |
          echo title: $title
          echo link: $link
          echo description: $description
          echo contentSnippet: $contentSnippet
          echo outputs: $outputs
          echo content: $content
          echo guid: $guid
          echo pubDate: $pubDate
      - name: Post To WeCom
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.WECOM_URL }}
          method: POST
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "content": "${{on.rss.outputs.title}} \n ${{on.rss.outputs.content}} \n 来源：${{on.rss.outputs.link}}"
              }
            }