on:
  rss:
    url: https://weekly.75.team/rss
    config:
      limit: 1
      timeZone: Asia/Shanghai
jobs:
  operation:
    name: Rss Operation
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          link: ${{on.rss.outputs.link}}
          pubDate: ${{on.rss.outputs.pubDate}}
          guid: ${{on.rss.outputs.guid}}
          content: ${{on.rss.outputs.content}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          description: ${{on.rss.outputs.description}}
          outputs: ${{on.rss.outputs}}
        run: |
          echo title: $title
          echo link: $link
          echo description: $description
          echo contentSnippet: $contentSnippet
          echo outputs: $outputs
          echo content: $content
          echo guid: $guid
          echo pubDate: $pubDate
      - name: rewrite url
        id: set-content
        uses: actions/github-script@v4
        env:
          content: ${{ on.rss.outputs.content }}
        with:
          result-encoding: string # 关键点 下面的 result 直接引用就是 string 类型
          script: |
            let { content } = process.env
            console.log("content is", content)
            let newContent = content.split('</h3>').map(i => {
                const patt = /(.*)href="(.*)">(.*)<\/a>/
                const [,,href, title] = i.match(patt) || []
                return href && title ? `[${title}](${href})` : null
            }).filter(i => i).join('\n')
            return newContent
      - name: Post To WeCom
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.WECOM_URL }}
          method: POST
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                "content": "${{on.rss.outputs.title}} \n ${{steps.set-content.outputs.result}} \n 来源：${{on.rss.outputs.link}}"
              }
            }