on:
  rss:
    url: https://weekly.75.team/rss
    config:
      limit: 1
      timeZone: Asia/Shanghai
jobs:
  operation:
    name: Rss Operation
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo link: $link
      - name: Post To WeCom
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.WECOM_URL }}
          method: POST
          body: |
            {
              "msgtype": "text",
              "text": {
                "content": "${{on.rss.outputs.title}} ${{steps.set-link.outputs.result}}"
              }
            }